export const CREATE_TOURNAMENT_REQUEST = 'CREATE_TOURNAMENT_REQUEST'
export const CREATE_TOURNAMENT_SUCCESS = 'CREATE_TOURNAMENT_SUCCESS'
export const CREATE_TOURNAMENT_FAIL = 'CREATE_TOURNAMENT_FAIL'
