const Data = [
  {
    index: 0,
    rank: '7',
    gameName: 'NBA2K',
    image1: '/images/nba.jpg',
    image2: '/images/nba.jpg',
    gamer1: 'Udosi',
    gamer2: 'IshiJi',
    mainImage: '/images/nba.jpg',
  },
  {
    index: 1,
    rank: '10',
    gameName: 'Fortnite',
    image1: '/images/nba.jpg',
    image2: '/images/nba.jpg',
    gamer1: 'Udosi',
    gamer2: 'IshiJi',
    mainImage: '/images/fortnite.jpg',
  },
  {
    index: 2,
    rank: '2',
    gameName: 'Grand Theft Auto',
    image1: '/images/nba.jpg',
    image2: '/images/nba.jpg',
    gamer1: 'Udosi',
    gamer2: 'IshiJi',
    mainImage: '/images/gta.jpg',
  },
  {
    index: 3,
    rank: '14',
    gameName: 'Call of Duty Warzone',
    image1: '/images/nba.jpg',
    image2: '/images/nba.jpg',
    gamer1: 'Udosi',
    gamer2: 'IshiJi',
    mainImage: '/images/warzone.jpg',
  },
  {
    index: 4,
    rank: '3',
    gameName: 'Fifa',
    image1: '/images/nba.jpg',
    image2: '/images/nba.jpg',
    gamer1: 'Udosi',
    gamer2: 'IshiJi',
    mainImage: '/images/fifa.jpg',
  },
  {
    index: 5,
    rank: '3',
    gameName: 'Fifa',
    image1: '/images/nba.jpg',
    image2: '/images/nba.jpg',
    gamer1: 'Udosi',
    gamer2: 'IshiJi',
    mainImage: '/images/fifa.jpg',
  },
  {
    index: 6,
    rank: '3',
    gameName: 'Fifa',
    image1: '/images/nba.jpg',
    image2: '/images/nba.jpg',
    gamer1: 'Udosi',
    gamer2: 'IshiJi',
    mainImage: '/images/fifa.jpg',
  },
]

export default Data
