const data: {
  _id: string
  index: number
  picture: string
  city: string
  address: string
  bedrooms: number
  bathrooms: number
  carSpaces: number
}[] = [
  {
    _id: '1',
    index: 0,
    picture: 'assets/pictures/optimized-catalogue2.jpg',
    city: 'Singer',
    address: '419 Road, Aba',
    bedrooms: 2,
    bathrooms: 2,
    carSpaces: 2,
  },
  {
    _id: '2',
    index: 1,
    picture: 'assets/pictures/optimized-catalogue1.jpg',
    city: 'Singer',
    address: '419 Road, Aba',
    bedrooms: 2,
    bathrooms: 2,
    carSpaces: 2,
  },
  {
    _id: '3',
    index: 2,
    picture: 'assets/pictures/optimized-catalogue3.jpg',
    city: 'Singer',
    address: '419 Road, Aba',
    bedrooms: 2,
    bathrooms: 2,
    carSpaces: 2,
  },
  {
    _id: '4',
    index: 3,
    picture: 'assets/pictures/optimized-catalogue4.jpg',
    city: 'Singer',
    address: '419 Road, Aba',
    bedrooms: 2,
    bathrooms: 2,
    carSpaces: 2,
  },
  {
    _id: '5',
    index: 4,
    picture: 'assets/pictures/optimized-catalogue5.jpg',
    city: 'Singer',
    address: '419 Road, Aba',
    bedrooms: 2,
    bathrooms: 2,
    carSpaces: 2,
  },
  {
    _id: '6',
    index: 5,
    picture: 'assets/pictures/optimized-catalogue6.jpg',
    city: 'Singer',
    address: '419 Road, Aba',
    bedrooms: 2,
    bathrooms: 2,
    carSpaces: 2,
  },
  {
    _id: '7',
    index: 6,
    picture: 'assets/pictures/optimized-catalogue7.jpg',
    city: 'Singer',
    address: '419 Road, Aba',
    bedrooms: 2,
    bathrooms: 2,
    carSpaces: 2,
  },
  {
    _id: '8',
    index: 7,
    picture: 'assets/pictures/optimized-catalogue8.jpg',
    city: 'Singer',
    address: '419 Road, Aba',
    bedrooms: 2,
    bathrooms: 2,
    carSpaces: 2,
  },
  {
    _id: '9',
    index: 8,
    picture: 'assets/pictures/optimized-catalogue9.jpg',
    city: 'Singer',
    address: '419 Road, Aba',
    bedrooms: 2,
    bathrooms: 2,
    carSpaces: 2,
  },
  {
    _id: '10',
    index: 9,
    picture: 'assets/pictures/optimized-catalogue2.jpg',
    city: 'Singer',
    address: '419 Road, Aba',
    bedrooms: 2,
    bathrooms: 2,
    carSpaces: 2,
  },

  {
    _id: '11',
    index: 10,
    picture: 'assets/pictures/optimized-catalogue8.jpg',
    city: 'Singer',
    address: '419 Road, Aba',
    bedrooms: 2,
    bathrooms: 2,
    carSpaces: 2,
  },
  {
    _id: '12',
    index: 11,
    picture: 'assets/pictures/optimized-catalogue6.jpg',
    city: 'Singer',
    address: '419 Road, Aba',
    bedrooms: 2,
    bathrooms: 2,
    carSpaces: 2,
  },
  {
    _id: '13',
    index: 12,
    picture: 'assets/pictures/optimized-catalogue9.jpg',
    city: 'Singer',
    address: '419 Road, Aba',
    bedrooms: 2,
    bathrooms: 2,
    carSpaces: 2,
  },
]

export default data
