const data = {
  properties: [
    {
      id: 1,
      data: [
        {
          _id: '1',
          index: 0,
          picture: `images/soldier4.png`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 1,
        },
        {
          _id: '2',
          index: 1,
          picture: `images/soldier1.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 2,
        },
        {
          _id: '3',
          index: 2,
          picture: `images/nba.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 3,
        },
        {
          _id: '4',
          index: 3,
          picture: `images/gta.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 2,
        },
      ],
    },

    {
      id: 2,
      data: [
        {
          _id: '1',
          index: 0,
          picture: `images/nba.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 0,
        },
        {
          _id: '2',
          index: 1,
          picture: `images/nba.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 3,
        },
        {
          _id: '3',
          index: 2,
          picture: `images/nba.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 5,
        },
        {
          _id: '4',
          index: 3,
          picture: `images/nba.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 2,
        },
      ],
    },

    {
      id: 1,
      data: [
        {
          _id: '1',
          index: 0,
          picture: `images/gta.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 1,
        },
        {
          _id: '2',
          index: 1,
          picture: `images/gta.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 1,
        },
        {
          _id: '3',
          index: 2,
          picture: `images/gta.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 5,
        },
        {
          _id: '4',
          index: 3,
          picture: `images/gta.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 2,
        },
      ],
    },

    {
      id: 1,
      data: [
        {
          _id: '1',
          index: 0,
          picture: `images/soldier4.png`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 1,
        },
        {
          _id: '2',
          index: 1,
          picture: `images/soldier1.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 1,
        },
        {
          _id: '3',
          index: 2,
          picture: `images/nba.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 5,
        },
        {
          _id: '4',
          index: 3,
          picture: `images/gta.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 2,
        },
      ],
    },

    {
      id: 1,
      data: [
        {
          _id: '1',
          index: 0,
          picture: `images/soldier4.png`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 1,
        },
        {
          _id: '2',
          index: 1,
          picture: `images/soldier1.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 1,
        },
        {
          _id: '3',
          index: 2,
          picture: `images/nba.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 5,
        },
        {
          _id: '4',
          index: 3,
          picture: `images/gta.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 2,
        },
      ],
    },

    {
      id: 1,
      data: [
        {
          _id: '1',
          index: 0,
          picture: `images/soldier4.png`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 1,
        },
        {
          _id: '2',
          index: 1,
          picture: `images/soldier1.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 1,
        },
        {
          _id: '3',
          index: 2,
          picture: `images/nba.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 5,
        },
        {
          _id: '4',
          index: 3,
          picture: `images/gta.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 2,
        },
      ],
    },

    {
      id: 1,
      data: [
        {
          _id: '1',
          index: 0,
          picture: `images/soldier4.png`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 1,
        },
        {
          _id: '2',
          index: 1,
          picture: `images/soldier1.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 1,
        },
        {
          _id: '3',
          index: 2,
          picture: `images/nba.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 5,
        },
        {
          _id: '4',
          index: 3,
          picture: `images/gta.jpg`,
          name: 'Singer',
          address: '419 Road, Aba',
          bedrooms: 2,
          bathrooms: 2,
          carSpaces: 2,
          next: 2,
        },
      ],
    },
  ],
}

export default data
